name: Expo CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint et Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Activer et configurer Corepack
        run: |
          corepack enable
          npm i -g corepack
          corepack prepare yarn@4.8.1 --activate

      - name: VÃ©rifier la version de Yarn
        run: yarn --version

      - name: Install dependencies
        run: yarn install

      - name: TypeScript Check
        run: yarn tsc --noEmit

      - name: Lint code
        run: yarn lint

      - name: Run tests
        run: yarn test --ci --passWithNoTests